# Generated by Django 2.1.1 on 2019-03-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardtitle', models.CharField(max_length=120)),
                ('Cardimage', models.ImageField(blank=True, upload_to='card_images')),
                ('CardDescription', models.TextField()),
                ('CardAssigned', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=120)),
                ('listorder', models.IntegerField()),
                ('listitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KanbanBoard.Card')),
            ],
        ),
    ]
