# Generated by Django 2.1.1 on 2018-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_persona',
            name='Picmage',
            field=models.ImageField(blank=True, upload_to='persona_images'),
        ),
    ]
