# Generated by Django 2.1.1 on 2019-01-04 23:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0006_auto_20190101_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desciption', models.TextField()),
                ('problems', models.TextField()),
                ('business_reasons', models.TextField()),
                ('impact', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('datecreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('area', models.CharField(choices=[('B', 'Backlog'), ('U', 'Unsorted'), ('C', 'Completed')], default='Unsorted', max_length=100)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a', to=settings.AUTH_USER_MODEL)),
                ('iProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.myProducts')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
