# Generated by Django 2.1.1 on 2018-11-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desciption', models.TextField()),
                ('problems', models.TextField()),
                ('business_reasons', models.TextField()),
                ('impact', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('createdby', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField()),
                ('area', models.CharField(choices=[('B', 'Backlog'), ('U', 'Unsorted'), ('C', 'Completed')], default='Unsorted', max_length=100)),
                ('i_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.myProducts')),
            ],
        ),
    ]
