# Generated by Django 2.1.1 on 2019-02-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='area',
            field=models.CharField(choices=[('B', 'Backlog'), ('U', 'Unsorted'), ('C', 'Completed'), ('O', 'Optimisation Testing'), ('I', 'In Progress'), ('I', 'Investigation'), ('D', 'Discovery')], default='Unsorted', max_length=100),
        ),
    ]
