# Generated by Django 2.1.1 on 2018-12-18 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0002_auto_20181117_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='datecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
