# Generated by Django 2.1.1 on 2019-01-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_useraccesslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesslist',
            name='User',
        ),
        migrations.AlterField(
            model_name='myproducts',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='useraccesslist',
            name='ProductAccessList',
        ),
        migrations.AddField(
            model_name='useraccesslist',
            name='ProductAccessList',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
