# Generated by Django 2.1.1 on 2019-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20190101_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesslist',
            name='Users',
            field=models.ManyToManyField(to='Products.myProducts'),
        ),
    ]
