# Generated by Django 2.1.1 on 2019-01-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_useraccesslist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproducts',
            name='User',
        ),
    ]
