# Generated by Django 2.1.1 on 2019-01-01 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0005_remove_myproducts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesslist',
            name='ProductAccessList',
        ),
        migrations.RemoveField(
            model_name='useraccesslist',
            name='Users',
        ),
        migrations.AddField(
            model_name='myproducts',
            name='ProductAccessList',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAccessList',
        ),
    ]
